package ws.rrd.mem;

import java.io.Serializable;

/** 
 * <b>Description:TODO</b>
 * @author      vipup<br>
 * <br>
 * <b>Copyright:</b>     Copyright (c) 2006-2008 Monster AG <br>
 * <b>Company:</b>       Monster AG  <br>
 * 
 * Creation:  26.07.2010::11:45:51<br> 
 */
public class ScriptItem implements Serializable{

	/**
	 * @author vipup
	 */
	private static final long serialVersionUID = -7937242057537348262L;
	private String value;

	public ScriptItem(String value) {
		this.value = value;
	}

	public String getValue() {
		//TODO 
		if (1 == 2)
			throw new RuntimeException(
					"autogenerated from vipup return not checked value since26.07.2010 ;)!");
		else
			return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}


 