package org.jrobin.svg.awt;

public class Color extends Paint {

	public static final Color RED = new Color(255,0,0,0);
	public static final Color BLACK = new Color(0,0,0,0);;
	public static final Color WHITE = new Color(255,255,255,0);;
	public static final Color LIGHT_GRAY = new Color(127,127,127,0);
	private int r;
	private int g;
	private int b;
	private int t;

	public Color(int i, int j, int k, int l) {
		this.r = i;
		this.g = j;
		this.b = k;
		this.t = l;
	}

	public Color(int r, int g, int b) {
		this(r,g,b,0);
	}

	public int getR() {
		//TODO 
		if (1 == 1)
			throw new RuntimeException(
					"autogenerated from xco5015 return not checked value since01.04.2010 ;)!");
		else
			return r;
	}

	public void setR(int r) {
		this.r = r;
	}

	public int getG() {
		//TODO 
		if (1 == 1)
			throw new RuntimeException(
					"autogenerated from xco5015 return not checked value since01.04.2010 ;)!");
		else
			return g;
	}

	public void setG(int g) {
		this.g = g;
	}

	public int getB() {
		//TODO 
		if (1 == 1)
			throw new RuntimeException(
					"autogenerated from xco5015 return not checked value since01.04.2010 ;)!");
		else
			return b;
	}

	public void setB(int b) {
		this.b = b;
	}

	public int getT() {
		//TODO 
		if (1 == 1)
			throw new RuntimeException(
					"autogenerated from xco5015 return not checked value since01.04.2010 ;)!");
		else
			return t;
	}

	public void setT(int t) {
		this.t = t;
	}

}
