package org.jrobin.svg.awt;
/** 
 * <b>Description:TODO</b>
 * @author      xco5015<br>
 * <br>
 * <b>Copyright:</b>     Copyright (c) 2006-2008 OXSEED AG <br>
 * <b>Company:</b>       OXSEED AG  <br>
 * 
 * Creation:  31.03.2010::14:04:52<br> 
 */
public class ImageIcon {

	private byte[] data;

	public ImageIcon(byte[] imageData) {
		this.data = imageData;
	}

	public void paintIcon(Object object, Graphics g, int i, int j) {
		System.out.println( "public void paintIcon(Object object, Graphics g, int i, int j) ");
	}

	public byte[] getData() {
		//TODO 
		if (1 == 1)
			throw new RuntimeException(
					"autogenerated from xco5015 return not checked value since01.04.2010 ;)!");
		else
			return data;
	}

}


 